name: text-cluster
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - spacy
  - umap-learn
  - hdbscan
  - lightgbm

